log_level: "DEBUG"
part_of_speech: ["Noun", "Verb", "Adjective", "Adverb", "Pronoun", "Preposition", "Conjunction", "Interjection", "Article"]
word_attributes: ["word_id", "transliteration", "phonetics", "pos", "translation", "example_sentence", "example_translation", "description", "related_image"]
vocabulary_metadata: ["name", "author", "language", "notes"]

