from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtCore import pyqtSlot
from PyQt5 import QtCore, QtGui, QtWidgets

from controllers import log

class main_frame(QMainWindow):
    def __init__(self):
        super().__init__()

        self._ui = Ui_MainWindow()
        self._ui.setupUi(self)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 767)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1031, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.Vocabulary = QtWidgets.QWidget()
        self.Vocabulary.setObjectName("Vocabulary")
        self.description = QtWidgets.QLabel(self.Vocabulary)
        self.description.setGeometry(QtCore.QRect(420, 440, 431, 121))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(10)
        self.description.setFont(font)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.translation_label = QtWidgets.QLabel(self.Vocabulary)
        self.translation_label.setGeometry(QtCore.QRect(540, 250, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std Light")
        font.setPointSize(24)
        font.setItalic(True)
        self.translation_label.setFont(font)
        self.translation_label.setObjectName("translation_label")
        self.example_sentence = QtWidgets.QLabel(self.Vocabulary)
        self.example_sentence.setGeometry(QtCore.QRect(420, 310, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        self.example_sentence.setFont(font)
        self.example_sentence.setWordWrap(True)
        self.example_sentence.setObjectName("example_sentence")
        self.rel_header = QtWidgets.QLabel(self.Vocabulary)
        self.rel_header.setGeometry(QtCore.QRect(450, 580, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rel_header.setFont(font)
        self.rel_header.setObjectName("rel_header")
        self.example_sentence_2 = QtWidgets.QLabel(self.Vocabulary)
        self.example_sentence_2.setGeometry(QtCore.QRect(420, 350, 431, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setItalic(True)
        self.example_sentence_2.setFont(font)
        self.example_sentence_2.setWordWrap(True)
        self.example_sentence_2.setObjectName("example_sentence_2")
        self.pos_label = QtWidgets.QLabel(self.Vocabulary)
        self.pos_label.setGeometry(QtCore.QRect(420, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pos_label.setFont(font)
        self.pos_label.setObjectName("pos_label")
        self.description_header = QtWidgets.QLabel(self.Vocabulary)
        self.description_header.setGeometry(QtCore.QRect(420, 400, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(14)
        self.description_header.setFont(font)
        self.description_header.setObjectName("description_header")
        self.word_label = QtWidgets.QLabel(self.Vocabulary)
        self.word_label.setGeometry(QtCore.QRect(420, 190, 441, 51))
        font = QtGui.QFont()
        font.setFamily("HelveticaNeueLT Std")
        font.setPointSize(36)
        self.word_label.setFont(font)
        self.word_label.setObjectName("word_label")
        self.word_image = QtWidgets.QGraphicsView(self.Vocabulary)
        self.word_image.setGeometry(QtCore.QRect(330, 0, 691, 161))
        self.word_image.setObjectName("word_image")
        self.vocab_tv = QtWidgets.QTreeView(self.Vocabulary)
        self.vocab_tv.setGeometry(QtCore.QRect(0, 0, 331, 691))
        self.vocab_tv.setObjectName("vocab_tv")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Vocabulary)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(450, 610, 391, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Helvetica LT Std")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 3, 1, 1)
        self.tabWidget.addTab(self.Vocabulary, "")
        self.Construction = QtWidgets.QWidget()
        self.Construction.setObjectName("Construction")
        self.horizontalSlider = QtWidgets.QSlider(self.Construction)
        self.horizontalSlider.setGeometry(QtCore.QRect(610, 90, 351, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.Construction)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(610, 150, 351, 22))
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.Construction)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(610, 210, 351, 22))
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.tabWidget.addTab(self.Construction, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuVocabulary = QtWidgets.QMenu(self.menubar)
        self.menuVocabulary.setObjectName("menuVocabulary")
        self.menuConstruction = QtWidgets.QMenu(self.menubar)
        self.menuConstruction.setObjectName("menuConstruction")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Vocabulary = QtWidgets.QAction(MainWindow)
        self.actionOpen_Vocabulary.setObjectName("actionOpen_Vocabulary")
        self.actionNew_Vocabulary = QtWidgets.QAction(MainWindow)
        self.actionNew_Vocabulary.setObjectName("actionNew_Vocabulary")
        self.actionClose_Vocabulary = QtWidgets.QAction(MainWindow)
        self.actionClose_Vocabulary.setObjectName("actionClose_Vocabulary")
        self.actionQuit_Program = QtWidgets.QAction(MainWindow)
        self.actionQuit_Program.setObjectName("actionQuit_Program")
        self.actionImport_xls_csv = QtWidgets.QAction(MainWindow)
        self.actionImport_xls_csv.setObjectName("actionImport_xls_csv")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.actionPopulate_Vocabulary = QtWidgets.QAction(MainWindow)
        self.actionPopulate_Vocabulary.setObjectName("actionPopulate_Vocabulary")
        self.actionShow_Stats = QtWidgets.QAction(MainWindow)
        self.actionShow_Stats.setObjectName("actionShow_Stats")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionFeed_Text = QtWidgets.QAction(MainWindow)
        self.actionFeed_Text.setObjectName("actionFeed_Text")
        self.menuFile.addAction(self.actionOpen_Vocabulary)
        self.menuFile.addAction(self.actionNew_Vocabulary)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose_Vocabulary)
        self.menuFile.addAction(self.actionQuit_Program)
        self.menuVocabulary.addAction(self.actionImport_xls_csv)
        self.menuVocabulary.addAction(self.actionExport)
        self.menuVocabulary.addSeparator()
        self.menuVocabulary.addAction(self.actionPopulate_Vocabulary)
        self.menuVocabulary.addAction(self.actionShow_Stats)
        self.menuConstruction.addAction(self.actionFeed_Text)
        self.menuHelp.addAction(self.actionInfo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuVocabulary.menuAction())
        self.menubar.addAction(self.menuConstruction.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.description.setText(_translate("MainWindow", "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."))
        self.translation_label.setText(_translate("MainWindow", "Translation"))
        self.example_sentence.setText(_translate("MainWindow", "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."))
        self.rel_header.setText(_translate("MainWindow", "Related Words"))
        self.example_sentence_2.setText(_translate("MainWindow", "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."))
        self.pos_label.setText(_translate("MainWindow", "Verb"))
        self.description_header.setText(_translate("MainWindow", "Description"))
        self.word_label.setText(_translate("MainWindow", "Word Item"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Vocabulary), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Construction), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuVocabulary.setTitle(_translate("MainWindow", "Vocabulary"))
        self.menuConstruction.setTitle(_translate("MainWindow", "Builder"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen_Vocabulary.setText(_translate("MainWindow", "Open Vocabulary"))
        self.actionNew_Vocabulary.setText(_translate("MainWindow", "New Vocabulary"))
        self.actionClose_Vocabulary.setText(_translate("MainWindow", "Close Vocabulary"))
        self.actionQuit_Program.setText(_translate("MainWindow", "Quit Program"))
        self.actionImport_xls_csv.setText(_translate("MainWindow", "Import xls/csv"))
        self.actionExport.setText(_translate("MainWindow", "Export..."))
        self.actionPopulate_Vocabulary.setText(_translate("MainWindow", "Populate Vocabulary..."))
        self.actionShow_Stats.setText(_translate("MainWindow", "Show Stats"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionFeed_Text.setText(_translate("MainWindow", "Feed Text..."))

    